quero_visitar = ['Quatar', 'Peru', 'Canadá', 'Japão', 'Patagônia']
print(quero_visitar)
print(sorted(quero_visitar))
print(quero_visitar)
print(sorted(quero_visitar, reverse=True))
print(quero_visitar)
quero_visitar.reverse()
print(quero_visitar)
quero_visitar.reverse()
print(quero_visitar)
quero_visitar.sort()
print(quero_visitar)
quero_visitar.sort(reverse=True)
print(quero_visitar)